/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { InlineResponse404 } from '../model/inlineResponse404';
import { PastExamsHubCoreApplicationExamsCommandCreateCreateExamCommand } from '../model/pastExamsHubCoreApplicationExamsCommandCreateCreateExamCommand';
import { PastExamsHubCoreApplicationExamsCommandCreateCreateExamCommandResult } from '../model/pastExamsHubCoreApplicationExamsCommandCreateCreateExamCommandResult';
import { PastExamsHubCoreApplicationExamsQueriesGetCollectionGetExamsQueryResult } from '../model/pastExamsHubCoreApplicationExamsQueriesGetCollectionGetExamsQueryResult';
import { PastExamsHubCoreApplicationExamsQueriesGetLatestExamsGetLatestExamsQuery } from '../model/pastExamsHubCoreApplicationExamsQueriesGetLatestExamsGetLatestExamsQuery';
import { PastExamsHubCoreApplicationExamsQueriesGetLatestExamsGetLatestExamsQueryResult } from '../model/pastExamsHubCoreApplicationExamsQueriesGetLatestExamsGetLatestExamsQueryResult';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class ExamsService {

    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param examPeriodUid 
     * @param courseUid 
     * @param pageNumber 
     * @param pageSize 
     * @param searchText 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public examsGet(examPeriodUid?: string, courseUid?: string, pageNumber?: number, pageSize?: number, searchText?: string, observe?: 'body', reportProgress?: boolean): Observable<PastExamsHubCoreApplicationExamsQueriesGetCollectionGetExamsQueryResult>;
    public examsGet(examPeriodUid?: string, courseUid?: string, pageNumber?: number, pageSize?: number, searchText?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PastExamsHubCoreApplicationExamsQueriesGetCollectionGetExamsQueryResult>>;
    public examsGet(examPeriodUid?: string, courseUid?: string, pageNumber?: number, pageSize?: number, searchText?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PastExamsHubCoreApplicationExamsQueriesGetCollectionGetExamsQueryResult>>;
    public examsGet(examPeriodUid?: string, courseUid?: string, pageNumber?: number, pageSize?: number, searchText?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {






        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (examPeriodUid !== undefined && examPeriodUid !== null) {
            queryParameters = queryParameters.set('ExamPeriodUid', <any>examPeriodUid);
        }
        if (courseUid !== undefined && courseUid !== null) {
            queryParameters = queryParameters.set('CourseUid', <any>courseUid);
        }
        if (pageNumber !== undefined && pageNumber !== null) {
            queryParameters = queryParameters.set('PageNumber', <any>pageNumber);
        }
        if (pageSize !== undefined && pageSize !== null) {
            queryParameters = queryParameters.set('PageSize', <any>pageSize);
        }
        if (searchText !== undefined && searchText !== null) {
            queryParameters = queryParameters.set('SearchText', <any>searchText);
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<PastExamsHubCoreApplicationExamsQueriesGetCollectionGetExamsQueryResult>('get',`${this.basePath}/Exams`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param request 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public examsLatestExamsGet(request?: PastExamsHubCoreApplicationExamsQueriesGetLatestExamsGetLatestExamsQuery, observe?: 'body', reportProgress?: boolean): Observable<PastExamsHubCoreApplicationExamsQueriesGetLatestExamsGetLatestExamsQueryResult>;
    public examsLatestExamsGet(request?: PastExamsHubCoreApplicationExamsQueriesGetLatestExamsGetLatestExamsQuery, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PastExamsHubCoreApplicationExamsQueriesGetLatestExamsGetLatestExamsQueryResult>>;
    public examsLatestExamsGet(request?: PastExamsHubCoreApplicationExamsQueriesGetLatestExamsGetLatestExamsQuery, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PastExamsHubCoreApplicationExamsQueriesGetLatestExamsGetLatestExamsQueryResult>>;
    public examsLatestExamsGet(request?: PastExamsHubCoreApplicationExamsQueriesGetLatestExamsGetLatestExamsQuery, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (request !== undefined && request !== null) {
            queryParameters = queryParameters.set('request', <any>request);
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<PastExamsHubCoreApplicationExamsQueriesGetLatestExamsGetLatestExamsQueryResult>('get',`${this.basePath}/Exams/LatestExams`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public examsPost(body?: PastExamsHubCoreApplicationExamsCommandCreateCreateExamCommand, observe?: 'body', reportProgress?: boolean): Observable<PastExamsHubCoreApplicationExamsCommandCreateCreateExamCommandResult>;
    public examsPost(body?: PastExamsHubCoreApplicationExamsCommandCreateCreateExamCommand, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PastExamsHubCoreApplicationExamsCommandCreateCreateExamCommandResult>>;
    public examsPost(body?: PastExamsHubCoreApplicationExamsCommandCreateCreateExamCommand, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PastExamsHubCoreApplicationExamsCommandCreateCreateExamCommandResult>>;
    public examsPost(body?: PastExamsHubCoreApplicationExamsCommandCreateCreateExamCommand, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<PastExamsHubCoreApplicationExamsCommandCreateCreateExamCommandResult>('post',`${this.basePath}/Exams`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
