/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PastExamsHubBaseDomainEnumsRoleType } from './pastExamsHubBaseDomainEnumsRoleType';
import { PastExamsHubCoreDomainEnumsExamPeriodType } from './pastExamsHubCoreDomainEnumsExamPeriodType';
import { PastExamsHubCoreDomainEnumsExamType } from './pastExamsHubCoreDomainEnumsExamType';

export interface PastExamsHubCoreApplicationExamSoultionsModelsExamSolutionModel { 
    ownerFirstName?: string;
    ownerLastName?: string;
    ownerStudyYear?: number;
    ownerRole?: PastExamsHubBaseDomainEnumsRoleType;
    comment?: string;
    createdDateTimeUtc?: Date;
    taskNumber?: number;
    gradeCount?: number;
    courseName?: string;
    type?: PastExamsHubCoreDomainEnumsExamType;
    periodName?: string;
    periodType?: PastExamsHubCoreDomainEnumsExamPeriodType;
}