/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type PastExamsHubCoreDomainEnumsExamPeriodType = 'Unknown' | 'January' | 'April' | 'June' | 'June2' | 'September' | 'October' | 'October2' | 'December';

export const PastExamsHubCoreDomainEnumsExamPeriodType = {
    Unknown: 'Unknown' as PastExamsHubCoreDomainEnumsExamPeriodType,
    January: 'January' as PastExamsHubCoreDomainEnumsExamPeriodType,
    April: 'April' as PastExamsHubCoreDomainEnumsExamPeriodType,
    June: 'June' as PastExamsHubCoreDomainEnumsExamPeriodType,
    June2: 'June2' as PastExamsHubCoreDomainEnumsExamPeriodType,
    September: 'September' as PastExamsHubCoreDomainEnumsExamPeriodType,
    October: 'October' as PastExamsHubCoreDomainEnumsExamPeriodType,
    October2: 'October2' as PastExamsHubCoreDomainEnumsExamPeriodType,
    December: 'December' as PastExamsHubCoreDomainEnumsExamPeriodType
};